### ISSUE TITLE
WordPress HEAD should be updated after each WordPress update

### ISSUE THREAD

**Issue by pdobrescu** [PressLabs/gitium-base#8]
We're still running with WP 4.0 in the Vagrant setup and we're already at 4.3.1 with 4.4 coming soon.

**Comment by Marius786** [comment]
I close this issue because of the following reasons:

There is no other sane solution for this issue. We must do it manually because we cannot follow the stable branch, because the name is changing all the time see https://github.com/WordPress/wordpress The master branch is not stable.
